lunchclub/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'recipe.views.landing_page'),
    url(r'^lunchclub/', include('recipe.urls')),
    url(r'^rehdernomics/', include('rehdernomics.urls')),
    url(r'^accounts/', include('account.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True, }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True, }),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
	        'document_root': settings.MEDIA_ROOT,
        }),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
	        'document_root': settings.STATIC_ROOT
        }),
    )

recipe/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView

from .models import Recipe
from .views import RecipeFeed, IngredientListView, IngredientRecipeList, RecipeDetailView


urlpatterns = patterns('recipe.views',
    url(r'^$', 'home', name='recipe_home'),
    url(r'^new_recipe/$', 'new_recipe', name="recipe_new"),
    url(r'^submit_recipe/$', 'submit_recipe', name="recipe_submit"),
    url(r'^submit_rating/$', 'submit_rating', name="recipe_rate"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{1,2})/(?P<slug>[-\w]+)/$',
         view=RecipeDetailView.as_view(),
         name='recipe_detail'),
    url(r'^ingredients/$', IngredientListView.as_view(), name="recipe_ingredient_list"),
    url(r'^ingredients/(?P<pk>\d+)/$', IngredientRecipeList.as_view(), name="recipe_ingredient_search"),
    url(r'^recipes/$', ListView.as_view(
        queryset=Recipe.objects.all().order_by("-created"),
        template_name="recipe/archives.html")),
    url(r'^tag/(?P<tag>\w+)$', 'tagpage'),
    url(r'^feed/$', RecipeFeed()),
)

recipe/models.py
from django import forms
from django.db import models
from django.conf import settings

from djangoratings.fields import RatingField

from .utils import unique_slugify


class Recipe(models.Model):
    """A single, self-contained recipe with ingredients."""
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=40, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    description = models.TextField()
    directions = models.TextField()
    ingredients = models.ManyToManyField('Ingredient', through="RecipeIngredient")
    image = models.ImageField(upload_to="recipes/%Y/%m/%d", null=True)
    rating = RatingField(range=5, weight=3) # 5 possible rating values, 1-5

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        url_name = "recipe_detail"
        self.save()
        kwargs = {
            "slug": self.slug,
            "year": self.created.year,
            "month": "%02d" % self.created.month,
            "day": self.created.day,
        }
        return (url_name, (), kwargs)

    def save(self, *args, **kwargs):
        slug_str = "%s" % (self.title)
        unique_slugify(self, slug_str)
        super(Recipe, self).save()


class Ingredient(models.Model):
    """One element in a recipe."""
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return "%s" % self.name


class RecipeIngredient(models.Model):
    """Contains additional information about each ingredient."""
    recipe = models.ForeignKey(Recipe)
    ingredient = models.ForeignKey(Ingredient)
    quantity = models.CharField(max_length=20)
    ingredient_state = models.CharField(max_length=30, default="", null=True)

    def __unicode__(self):
        return "%s %s %s" % (
            self.quantity, self.ingredient_state, self.ingredient
        )

    def description(self):
        return "%s %s %s" % (
            self.quantity, self.ingredient_state, self.ingredient
        )

recipe/forms.py
from django import forms

from crispy_forms.helper import FormHelper

from .widgets import StarsRadioFieldRenderer


class RecipeForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class':'name_field'}),
        label="Name",
        max_length=100,
        required=True,
    )

    description = forms.CharField(
        widget=forms.TextInput(attrs={'class':'description_field'}),
        label="Description",
        required=True,
    )

    directions = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'direction_field'}),
        label="Directions",
        required=True,
    )

    image = forms.ImageField(
        label="Image",
        required=True,
    )

    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-recipe_form'
        self.helper.form_tag = False
        self.helper.form_class = 'recipe_form'


class RecipeRatingForm(forms.Form):
    RATING_CHOICES = [(x, x) for x in xrange(1, 6)]
    rating = forms.ChoiceField(
        widget=forms.RadioSelect(
            renderer=StarsRadioFieldRenderer,
            attrs={'class': 'star'},
        ),
        choices=RATING_CHOICES,
    )


class IngredientForm(forms.Form):
    name = forms.CharField(
        label="Name",
        required=False,
    )

    quantity = forms.CharField(
        label="Quantity",
        required=False,
    )

    state = forms.CharField(
        label="State (chopped, minced, etc.)",
        required=False,
    )


class IngredientFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(IngredientFormSetHelper, self).__init__(*args, **kwargs)
        self.form_class = "ingredient_form"
        self.render_required_fields = True
        self.form_tag = False
        self.template = 'bootstrap/table_inline_formset.html'

recipe/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.contrib.syndication.views import Feed
from django.contrib.auth.decorators import login_required
from django.forms.formsets import formset_factory
from django.views.generic import ListView, DetailView

from .models import Recipe, Ingredient, RecipeIngredient
from .forms import RecipeForm, IngredientForm, IngredientFormSetHelper, RecipeRatingForm


def landing_page(request):
    return render(request, 'landing_page.html')


def home(request):
    context = {'recipes': Recipe.objects.all().order_by('-created')}
    return render(request, 'recipe/home.html', context)


def tagpage(request, tag):
    recipes = Recipe.objects.filter(tags__name=tag)
    return render(request, "recipe/tagpage.html", {
        "recipes": recipes,
        "tag": tag
    })


@login_required(redirect_field_name='redirect_to')
def new_recipe(request):
    recipe_form = RecipeForm(prefix="recipe")
    ingredient_formset = formset_factory(IngredientForm, extra=3)
    ingredient_formset_helper = IngredientFormSetHelper()
    return render(request, 'recipe/new_recipe.html', {
        'recipe_form': recipe_form,
        'ingredient_formset': ingredient_formset(prefix="ingredient"),
        'ingredient_formset_helper': ingredient_formset_helper,
    })


class RecipeDetailView(DetailView):
    template_name = "recipe/detail.html"
    model = Recipe

    def get_context_data(self, **kwargs):
        context = super(RecipeDetailView, self).get_context_data(**kwargs)
        context['recipe_rating_form'] = RecipeRatingForm()
        return context



class IngredientListView(ListView):
    context_object_name = "ingredients"
    template_name = "recipe/ingredient_list.html"
    queryset = Ingredient.objects.all()


class IngredientRecipeList(ListView):
    context_object_name = "recipes"
    template_name = "recipe/ingredient_recipes.html"
    model = Ingredient

    def get_queryset(self):
        self.ingredient = get_object_or_404(Ingredient, pk=self.kwargs['pk'])
        return Recipe.objects.filter(ingredients__name=self.ingredient.name)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(IngredientRecipeList, self).get_context_data(**kwargs)
        context['ingredient'] = self.ingredient
        return context


def submit_rating(request):
    if request.method == "POST":
        recipe_id = request.POST["recipe_id"]
        rating_id = request.POST['rating_id']
        rating = int(rating_id[-1]) + 1
        recipe = get_object_or_404(Recipe, pk=recipe_id)

        recipe.rating.add(score=rating, user=request.user, ip_address=request.META['REMOTE_ADDR'])
        print "Saved rating", rating

    return None

def submit_recipe(request):
    if request.method == "POST":
        recipe_form = RecipeForm(request.POST, request.FILES, prefix="recipe")
        ingredient_formset = formset_factory(IngredientForm)
        ingredient_form = ingredient_formset(request.POST, prefix="ingredient")
        if recipe_form.is_valid() and ingredient_form.is_valid():
            r_info = recipe_form.cleaned_data
            recipe = Recipe.objects.create(
                title=r_info['name'],
                author=request.user,
                description=r_info['description'],
                directions=r_info['directions'],
                image=r_info['image'],
            )

            for i_info in ingredient_form.cleaned_data:
                if not i_info:
                    continue

                name = i_info['name']
                ingredient, created = Ingredient.objects.get_or_create(name=name)
                requirement = RecipeIngredient.objects.create(
                    recipe=recipe,
                    ingredient=ingredient,
                    quantity=i_info['quantity'],
                    ingredient_state=i_info['state'],
                )

            return redirect(recipe.get_absolute_url())

        return redirect('recipe_new')


class RecipeFeed(Feed):
    title = "Lunch Club Recipes"
    description = "Recipes from the Lunch Club."
    link = "/lunchclub/feed"

    def items(self):
        return Recipe.objects.all().order_by("-created")[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.body

    def item_link(self, item):
        return u"/recipe/%d" % item.id

templates/recipe/avg_rating_snippet.html
<div class="rating">
    {% with votes=recipe.rating.votes %}
        {% include "recipe/rating_snippet.html" with rating=recipe.rating.score name=recipe.id %} ({{ recipe.rating.votes }} vote{{ votes|pluralize }})
    {% endwith %}
</div>

templates/recipe/base.html
{% extends "base.html" %}

{% block additional_css %}
	{% load staticfiles %}
    <link href="{% static 'css/lunchclub.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'star-rating/jquery.rating.css' %}">
{% endblock additional_css %}

{% block top_nav %}
{% endblock %}

{% block left_nav %}
    <div class="well sidebar-nav">
        <ul class="nav nav-list">
            <li><a href="{% url 'recipe_home' %}">Recipes</a></li>
            <li><a href="{% url 'recipe_ingredient_list' %}">Ingredients</a></li>
            <li><a href="#">Members</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </div>
{% endblock %}

{% block right_nav %}
{% endblock %}

templates/recipe/detail.html
{% extends "recipe/base.html" %}

{% block page_title %}{{ recipe.title|title }} | {% endblock page_title %}


{% load crispy_forms_tags %}
{% load staticfiles %}
{% load thumbnail %}
{% load get_range %}
{% load ratings %}

{% block script %}
    <script type="text/javascript" src="{% static 'star-rating/jquery.rating.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/csrf-token.js' %}"></script>
    <script>
    $(document).ready(function() {
        $(".star").click(function() {
            var rating_id = $(this).attr("id");
            $.ajax({
                type: 'POST',
                url: "{% url 'recipe_rate' %}",
                data: {"recipe_id": {{ recipe.id }}, "rating_id": rating_id}
                ,
                dataType: 'json',
                success: function(data){
                    if (data){

                    }
                    else{
                        confirm(data.status);
                    }
                }
            });
        });
    })
    </script>
{% endblock script %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'star-rating/jquery.rating.css' %}">
{% endblock additional_css %}

{% block page_content %}
    <div class="well">
        <div class="row-fluid">
            <div class="span5">
                {% if recipe.image %}
                    <a href="{{ recipe.image.url }}">
                        <img src="{{ recipe.image.url }}">
                    </a>
                {% else %}
                    No Image. Add your own!
                {% endif %}
            </div>

            <div class="span6 offset1">
                <h2><a href="{{ recipe.get_absolute_url }}">{{ recipe.title|title }}</a></h2>
                <p>by {{ recipe.author }} on {{ recipe.created }}</p>
                <p>{{ recipe.description|linebreaks }}</p>
                {% if user.is_authenticated %}
                    {% rating_by_user user on recipe.rating as vote %}
                    {% if not vote %}
                        {{ recipe_rating_form.as_p }}
                    {% else %}
                        Your Vote:
                        <div class="rating">
                            {% include "recipe/rating_snippet.html" with rating=vote %}
                        </div>
                    {% endif %}
                    <hr>
                {% endif %}
                <p>Average: {% include "recipe/avg_rating_snippet.html" with recipe=recipe %} </p>
            </div>

        </div>

        <hr />

        <h3>Ingredients</h3>
        <ul>
            {% for ingredient in recipe.recipeingredient_set.all %}
                <li>{{ ingredient|title }}</li>
            {% endfor %}
        </ul>

        <h3>Directions</h3>
        <p>{{ recipe.directions|linebreaks }}</p>
        </ul>
    </div>
{% endblock page_content %}

templates/recipe/home.html
{% extends "recipe/base.html" %}

{% block page_title %}Lunch Club Recipes | {% endblock page_title %}

{% block head %}
    {% load thumbnail %}
    {% load ratings %}
    {% load staticfiles %}
{% endblock head %}

{% block script %}
    <script type="text/javascript" src="{% static 'star-rating/jquery.rating.js' %}"></script>
{% endblock script %}

{% block page_content %}
    <h1>Lunch Club Recipes</h1>
    {% for recipe in recipes %}
        <div class="well">
            <div class="row">
                <div class="span4">
                {% if recipe.image %}
                    <a href="{{ recipe.get_absolute_url }}">
                        <img src="{{ recipe.image|thumbnail_url:'recipe_thumb' }}">
                    </a>
                {% endif %}
                </div>

                <div class="span6 offset1">
                    <ul class="recipe-summary">
                        <li><a href="{{ recipe.get_absolute_url }}">{{ recipe.title|title }}</a></li>
                        <li>by {{ recipe.author }} on {{ recipe.created }}</li>
                        <li>{% include "recipe/avg_rating_snippet.html" with recipe=recipe %}</li>
                    </ul>
                </div>
            </div>
        </div>
    {% empty %}
        Hm, doesn't look like there's any recipes yet! Please check back soon.
        <br>
    {% endfor %}
    <a class="btn btn-primary" href="{% url 'recipe_new' %}">Submit Recipe</a>
{% endblock page_content %}

templates/recipe/ingredient_list.html
{% extends "recipe/base.html" %}

{% block page_title %}Lunch Club Recipes | {% endblock page_title %}

{% load ratings %}

{% block page_content %}
    <h1>Ingredients</h1>
    <ul>
    {% for ingredient in ingredients %}
        <li><a href="{% url 'recipe_ingredient_search' ingredient.id %}">{{ ingredient.name|title }}</a></li>
    {% endfor %}
    </ul>
{% endblock page_content %}

templates/recipe/ingredient_recipes.html
{% extends "recipe/base.html" %}

{% block page_title %}Lunch Club Recipes | {% endblock page_title %}

{% load ratings %}

{% block page_content %}
    <h2>Recipes with {{ ingredient|title }}</h2>
    {% for recipe in recipes %}
        <div class="well">
            <div class="row">
                <div class="span4">
                {% if recipe.image %}
                    <img class="recipe-image" src="{{ recipe.image.url }}">
                {% else %}
                    <img class="recipe-image" src="http://placehold.it/200x150">
                {% endif %}
                </div>
                <div class="span6 offset1">
                    <a href="{{ recipe.get_absolute_url }}">{{ recipe.title|title }}</a>
                    <p>by {{ recipe.author }} on {{ recipe.created }}</p>
                    <p>Rating: {{ recipe.rating.score }} ({{ recipe.rating.votes }} reviews)</p>
                </div>
            </div>
        </div>
    {% empty %}
        Hm, doesn't look like there's any recipes yet! Please check back soon.
        <br>
    {% endfor %}
    <a class="btn btn-primary" href="{% url 'recipe_new' %}">Submit Recipe</a>
{% endblock page_content %}

templates/recipe/list.html
{% extends "blog/base.html" %}

Loop start!


{% block content %}
    <br>
    {% for post in posts %}
        {{ post.title }}
        <br>
        {{ post.body }}
        <br>
    {% endfor %}

    End of loop!
{% endblock content %}

templates/recipe/new_recipe.html
{% extends "recipe/base.html" %}

{% load crispy_forms_tags %}
{% load staticfiles %}

{% block script %}
<script type="text/javascript" src="{% static 'js/lunchclub.new-recipe.js' %}"></script>
<script>
    $('#add_more').click(function() {
        cloneMore('tr:last', 'ingredient');
    });

   $( "#full-recipe-form" ).submit(function( event ) {
        var fields = ["name", "description", "directions", "image"]
        for (fieldnum in fields) {
            fieldname = fields[fieldnum];
            if ($("#id_recipe-" + fieldname).val() == "") {
                alert("Please enter the recipe " + fieldname + ".");
                $("#id_recipe-" + fieldname).focus();
                event.preventDefault();
                return;
            }
        }
    });
</script>
{% endblock script %}

{% block page_content %}
    <form id="full-recipe-form" action="{% url 'recipe_submit' %}" method="post" enctype="multipart/form-data">
        <h5>Recipe</h5>
        {% crispy recipe_form recipe_form.helper %}

        <h5>Ingredients</h5>
        {% crispy ingredient_formset  ingredient_formset_helper %}
        <input type="button" value="Add Ingredient" id="add_more">

        <br>
        <input type="submit" class="submit-recipe btn btn-primary" value="Save Recipe" method="post"/>
    </form>
{% endblock page_content %}

templates/recipe/rating_snippet.html
{% load get_range %}

{% for x in 5|get_range %}
    <input name="{{ name }}" type="radio" class="star" disabled="disabled"
        {% if x < rating %}
            checked="checked"
        {% endif %}
    />
{% endfor %}